name             'usercreation'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures usercreation'
long_description 'Installs/Configures usercreation'
version          '0.1.0'
